#!/usr/bin/env bash

################################
# Shows info about connected batteries.
#
# Dependencies:
# - acpi
#
# @return {Number(%)}: Current battery charge
################################

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0


# Exit if no battery was found
if [ "$(acpi)" == "" ]; then exit 0; fi


state=$(acpi | sed -n 's/Battery [0-9]: \([A-Z]\).*, .*/\1/p')
chg=$(acpi | sed -n 's/Battery [0-9]:.*, \([0-9]\{1,3\}\)%.*/\1/p')


# Charging or Unknown
if [ $state = "C" ] || [ $state = "U" ]; then
	icon=""
	color=\#66FF33
else
	if [ $chg -le 20 ]; 
	then
		icon=""
		status=33
		color=\#FF0000
	elif [ $chg -le 60 ]; 
	then
		icon=""
		color=\#FFFF00
        else 
                icon=""
		color=\#009900
	fi
fi

full="$icon $chg%"
short="$chg%"

echo $full
echo $short
echo $color
exit $status
