#!/usr/bin/env bash

################################
# Shows unread gmail emails for the configured account.
#
# Dependencies:
# curl
#
# @return {Number(%)}: Current battery charge
################################


USER=rafael.saraiva132@gmail.com
PASS=portugal132
 
COUNT=`curl -su $USER:$PASS https://mail.google.com/mail/feed/atom || echo "<fullcount>unknown number of</fullcount>"`
COUNT=`echo "$COUNT" | grep "<fullcount>" | sed -e s/"<fullcount>"// -e s/"<\/fullcount>"//`
echo $COUNT
if [ "$COUNT" != "0" ]; then
    if [ "$COUNT" = "1" ];then
        WORD="mail";
    else
        WORD="mails";
    fi
fi
